version: '3'
services:
  emotions:
    build: ./emotion-service
    ports:
      - "3002:3002"
    networks:
      - webapp-network
  slp-keyword:
    build: ./slp-keyword
    ports:
      - "3003:3003"
    networks:
      - webapp-network
  audio-to-text:
    build: ./audio_to_text
    ports:
      - "3004:3004"
    networks:
      - webapp-network
  asr:
    build: ./ASR
    ports:
      - "3005:3005"
    networks:
      - webapp-network

  speaker-diarization:
    build: ./speakerDiarization
    ports:
      - "3006:3006"
    networks:
      - webapp-network

  speaker-classifier:
    build: ./Speakerclassifier
    ports:
      - "3007:3007"
    networks:
      - webapp-network
  
  asr-latest:
    build: ./asrlatest
    ports:
      - "3008:3008"
    networks:
      - webapp-network

  speechactivity-recognition:
      build: ./speechactivityrecognition
      ports:
        - "3009:3009"
      networks:
        - webapp-network

networks:
  webapp-network:
    driver: bridge
